Dockerfile with Jupyter, Python 3 and R-studio
cellcomplexitylab/themisto pull request #2
Opened 2020-11-21 09:02 UTC by yipryan2

This new Dockerfile includes Jupyter, Python 3 and R-studio. In addition, I have included the development package for python 3 to make sure C plug-in will work.

2020-11-21 18:47 UTC, gui11aume requested changes
1. R Studio does not seem to be installed by this Docker file.
2. The pull request should not be into the main branch of the repository.

2020-11-22 00:20 UTC, gui11aume commented
I have switched the pull request to branch `dev`, which addresses point 2 above.

2020-11-22 04:30 UTC, yipryan2 commented
I have committed my change to install R-studio version 1.3.959.

2020-11-22 18:35 UTC, gui11aume approved these changes

2020-11-22 18:35 UTC, merged